### ISSUE TITLE
Minimum size is too large.

### ISSUE THREAD

**Issue by Uradamus** [antoine-roux/krita-plugin-reference#2]
Thanks for this plugin, very handy, but by default it is very greedy with its minimum screen real estate use. It seems to be due to line 34 in the reference.py script where you used QSizePolicy.MinimumExpanding for both axes.

Switching those to QSizePolicy.Expanding seems to remove the annoying minimum size issue and allows for the docker to be shrunk down a lot smaller than it would be possible otherwise.

**Comment by antoine-roux** [comment]
Hello @Uradamus and sorry for the late answer.
Thank you for noticing this problem, I just commited your correction.
