### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [antoine-roux/krita-plugin-reference#3]
Hello!

I found link to this project from the fork https://github.com/Deevad/krita-plugin-reference

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by antoine-roux** [comment]
Hello,

Of course, I don't want to keep this source-code for myself :)
It was obvious for me, until you ask ;) The LICENCE file is now added!

Thanks for your useful remark

**Comment by vazhnov** [comment]
GPL-3.0 — cool! Thank you very much!
